name: Android CI

on:
  push:
    branches: [ developer, master ]
  pull_request:
    branches: [ developer, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run Ktlint
      run: ./gradlew ktlint
    - name: Run Detekt
      run: ./gradlew detekt
    - name: Build with Gradle
      run: ./gradlew build
      
      
