name: Android CI

on:
  push:
    branches: [ develop, master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Bash
      run: .ci/scripts/run.bash
      
      
